/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateContributorArgs } from "./CreateContributorArgs";
import { UpdateContributorArgs } from "./UpdateContributorArgs";
import { DeleteContributorArgs } from "./DeleteContributorArgs";
import { ContributorFindManyArgs } from "./ContributorFindManyArgs";
import { ContributorFindUniqueArgs } from "./ContributorFindUniqueArgs";
import { Contributor } from "./Contributor";
import { HealthAreaFindManyArgs } from "../../healthArea/base/HealthAreaFindManyArgs";
import { HealthArea } from "../../healthArea/base/HealthArea";
import { ObjectiveFindManyArgs } from "../../objective/base/ObjectiveFindManyArgs";
import { Objective } from "../../objective/base/Objective";
import { ContributorService } from "../contributor.service";

@graphql.Resolver(() => Contributor)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ContributorResolverBase {
  constructor(
    protected readonly service: ContributorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "any",
  })
  async _contributorsMeta(
    @graphql.Args() args: ContributorFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Contributor])
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "any",
  })
  async contributors(
    @graphql.Args() args: ContributorFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Contributor[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Contributor",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Contributor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "own",
  })
  async contributor(
    @graphql.Args() args: ContributorFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Contributor | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Contributor",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Contributor)
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "create",
    possession: "any",
  })
  async createContributor(
    @graphql.Args() args: CreateContributorArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Contributor> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Contributor"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Contributor)
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "update",
    possession: "any",
  })
  async updateContributor(
    @graphql.Args() args: UpdateContributorArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Contributor | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Contributor"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Contributor)
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "delete",
    possession: "any",
  })
  async deleteContributor(
    @graphql.Args() args: DeleteContributorArgs
  ): Promise<Contributor | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [HealthArea])
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "any",
  })
  async heathArea(
    @graphql.Parent() parent: Contributor,
    @graphql.Args() args: HealthAreaFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HealthArea[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "HealthArea",
    });
    const results = await this.service.findHeathArea(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Objective])
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "any",
  })
  async objectives(
    @graphql.Parent() parent: Contributor,
    @graphql.Args() args: ObjectiveFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Objective[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Objective",
    });
    const results = await this.service.findObjectives(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
