/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ContributorService } from "../contributor.service";
import { ContributorCreateInput } from "./ContributorCreateInput";
import { ContributorWhereInput } from "./ContributorWhereInput";
import { ContributorWhereUniqueInput } from "./ContributorWhereUniqueInput";
import { ContributorFindManyArgs } from "./ContributorFindManyArgs";
import { ContributorUpdateInput } from "./ContributorUpdateInput";
import { Contributor } from "./Contributor";
import { HealthAreaFindManyArgs } from "../../healthArea/base/HealthAreaFindManyArgs";
import { HealthArea } from "../../healthArea/base/HealthArea";
import { HealthAreaWhereUniqueInput } from "../../healthArea/base/HealthAreaWhereUniqueInput";
import { ObjectiveFindManyArgs } from "../../objective/base/ObjectiveFindManyArgs";
import { Objective } from "../../objective/base/Objective";
import { ObjectiveWhereUniqueInput } from "../../objective/base/ObjectiveWhereUniqueInput";
@swagger.ApiBearerAuth()
export class ContributorControllerBase {
  constructor(
    protected readonly service: ContributorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: Contributor })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ContributorCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Contributor> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Contributor"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: data,
      select: {
        comune: true,
        contributorName: true,
        countryOfOrigin: true,
        createdAt: true,
        id: true,
        municipality: true,
        numberOfColaborators: true,
        organizationType: true,
        province: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [Contributor] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ContributorFindManyArgs)
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Contributor[]> {
    const args = plainToClass(ContributorFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Contributor",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        comune: true,
        contributorName: true,
        countryOfOrigin: true,
        createdAt: true,
        id: true,
        municipality: true,
        numberOfColaborators: true,
        organizationType: true,
        province: true,
        updatedAt: true,
      },
    });
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: Contributor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ContributorWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Contributor | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Contributor",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        comune: true,
        contributorName: true,
        countryOfOrigin: true,
        createdAt: true,
        id: true,
        municipality: true,
        numberOfColaborators: true,
        organizationType: true,
        province: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Contributor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ContributorWhereUniqueInput,
    @common.Body()
    data: ContributorUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Contributor | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Contributor"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          comune: true,
          contributorName: true,
          countryOfOrigin: true,
          createdAt: true,
          id: true,
          municipality: true,
          numberOfColaborators: true,
          organizationType: true,
          province: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Contributor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ContributorWhereUniqueInput
  ): Promise<Contributor | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          comune: true,
          contributorName: true,
          countryOfOrigin: true,
          createdAt: true,
          id: true,
          municipality: true,
          numberOfColaborators: true,
          organizationType: true,
          province: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id/heathArea")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "any",
  })
  @ApiNestedQuery(HealthAreaFindManyArgs)
  async findManyHeathArea(
    @common.Req() request: Request,
    @common.Param() params: ContributorWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<HealthArea[]> {
    const query = plainToClass(HealthAreaFindManyArgs, request.query);
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "HealthArea",
    });
    const results = await this.service.findHeathArea(params.id, {
      ...query,
      select: {
        createdAt: true,
        healthfield: true,
        id: true,
        mainAreas: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post("/:id/heathArea")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "update",
    possession: "any",
  })
  async createHeathArea(
    @common.Param() params: ContributorWhereUniqueInput,
    @common.Body() body: ContributorWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      heathArea: {
        connect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Contributor"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id/heathArea")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "update",
    possession: "any",
  })
  async updateHeathArea(
    @common.Param() params: ContributorWhereUniqueInput,
    @common.Body() body: HealthAreaWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      heathArea: {
        set: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Contributor"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id/heathArea")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "update",
    possession: "any",
  })
  async deleteHeathArea(
    @common.Param() params: ContributorWhereUniqueInput,
    @common.Body() body: ContributorWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      heathArea: {
        disconnect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Contributor"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id/objectives")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "read",
    possession: "any",
  })
  @ApiNestedQuery(ObjectiveFindManyArgs)
  async findManyObjectives(
    @common.Req() request: Request,
    @common.Param() params: ContributorWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Objective[]> {
    const query = plainToClass(ObjectiveFindManyArgs, request.query);
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Objective",
    });
    const results = await this.service.findObjectives(params.id, {
      ...query,
      select: {
        actualStatus: true,
        createdAt: true,
        expectedStatus: true,
        id: true,

        objective: {
          select: {
            id: true,
          },
        },

        timeframe: true,
        unit: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post("/:id/objectives")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "update",
    possession: "any",
  })
  async createObjectives(
    @common.Param() params: ContributorWhereUniqueInput,
    @common.Body() body: ContributorWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      objectives: {
        connect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Contributor"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id/objectives")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "update",
    possession: "any",
  })
  async updateObjectives(
    @common.Param() params: ContributorWhereUniqueInput,
    @common.Body() body: ObjectiveWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      objectives: {
        set: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Contributor"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id/objectives")
  @nestAccessControl.UseRoles({
    resource: "Contributor",
    action: "update",
    possession: "any",
  })
  async deleteObjectives(
    @common.Param() params: ContributorWhereUniqueInput,
    @common.Body() body: ContributorWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      objectives: {
        disconnect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Contributor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"Contributor"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
