/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { HealthAreaCreateNestedManyWithoutContributorsInput } from "./HealthAreaCreateNestedManyWithoutContributorsInput";
import { Type } from "class-transformer";
import { ObjectiveCreateNestedManyWithoutContributorsInput } from "./ObjectiveCreateNestedManyWithoutContributorsInput";
@InputType()
class ContributorCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  comune?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contributorName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  countryOfOrigin?: string | null;

  @ApiProperty({
    required: false,
    type: () => HealthAreaCreateNestedManyWithoutContributorsInput,
  })
  @ValidateNested()
  @Type(() => HealthAreaCreateNestedManyWithoutContributorsInput)
  @IsOptional()
  @Field(() => HealthAreaCreateNestedManyWithoutContributorsInput, {
    nullable: true,
  })
  heathArea?: HealthAreaCreateNestedManyWithoutContributorsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  municipality?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numberOfColaborators?: string | null;

  @ApiProperty({
    required: false,
    type: () => ObjectiveCreateNestedManyWithoutContributorsInput,
  })
  @ValidateNested()
  @Type(() => ObjectiveCreateNestedManyWithoutContributorsInput)
  @IsOptional()
  @Field(() => ObjectiveCreateNestedManyWithoutContributorsInput, {
    nullable: true,
  })
  objectives?: ObjectiveCreateNestedManyWithoutContributorsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  organizationType?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  province?: string | null;
}
export { ContributorCreateInput };
