/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateObjectiveArgs } from "./CreateObjectiveArgs";
import { UpdateObjectiveArgs } from "./UpdateObjectiveArgs";
import { DeleteObjectiveArgs } from "./DeleteObjectiveArgs";
import { ObjectiveFindManyArgs } from "./ObjectiveFindManyArgs";
import { ObjectiveFindUniqueArgs } from "./ObjectiveFindUniqueArgs";
import { Objective } from "./Objective";
import { ContributorFindManyArgs } from "../../contributor/base/ContributorFindManyArgs";
import { Contributor } from "../../contributor/base/Contributor";
import { ObjectiveService } from "../objective.service";

@graphql.Resolver(() => Objective)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ObjectiveResolverBase {
  constructor(
    protected readonly service: ObjectiveService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "read",
    possession: "any",
  })
  async _objectivesMeta(
    @graphql.Args() args: ObjectiveFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Objective])
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "read",
    possession: "any",
  })
  async objectives(
    @graphql.Args() args: ObjectiveFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Objective[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Objective",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Objective, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "read",
    possession: "own",
  })
  async objective(
    @graphql.Args() args: ObjectiveFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Objective | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Objective",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Objective)
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "create",
    possession: "any",
  })
  async createObjective(
    @graphql.Args() args: CreateObjectiveArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Objective> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Objective",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Objective"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        objective: args.data.objective
          ? {
              connect: args.data.objective,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Objective)
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "update",
    possession: "any",
  })
  async updateObjective(
    @graphql.Args() args: UpdateObjectiveArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Objective | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Objective",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Objective"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          objective: args.data.objective
            ? {
                connect: args.data.objective,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Objective)
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "delete",
    possession: "any",
  })
  async deleteObjective(
    @graphql.Args() args: DeleteObjectiveArgs
  ): Promise<Objective | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Contributor])
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "read",
    possession: "any",
  })
  async contributor(
    @graphql.Parent() parent: Objective,
    @graphql.Args() args: ContributorFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Contributor[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Contributor",
    });
    const results = await this.service.findContributor(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Objective])
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "read",
    possession: "any",
  })
  async objectives(
    @graphql.Parent() parent: Objective,
    @graphql.Args() args: ObjectiveFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Objective[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Objective",
    });
    const results = await this.service.findObjectives(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Objective, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "read",
    possession: "any",
  })
  async objective(
    @graphql.Parent() parent: Objective,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Objective | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Objective",
    });
    const result = await this.service.getObjective(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
