/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateHealthAreaArgs } from "./CreateHealthAreaArgs";
import { UpdateHealthAreaArgs } from "./UpdateHealthAreaArgs";
import { DeleteHealthAreaArgs } from "./DeleteHealthAreaArgs";
import { HealthAreaFindManyArgs } from "./HealthAreaFindManyArgs";
import { HealthAreaFindUniqueArgs } from "./HealthAreaFindUniqueArgs";
import { HealthArea } from "./HealthArea";
import { ContributorFindManyArgs } from "../../contributor/base/ContributorFindManyArgs";
import { Contributor } from "../../contributor/base/Contributor";
import { HealthAreaService } from "../healthArea.service";

@graphql.Resolver(() => HealthArea)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class HealthAreaResolverBase {
  constructor(
    protected readonly service: HealthAreaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "HealthArea",
    action: "read",
    possession: "any",
  })
  async _healthAreasMeta(
    @graphql.Args() args: HealthAreaFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [HealthArea])
  @nestAccessControl.UseRoles({
    resource: "HealthArea",
    action: "read",
    possession: "any",
  })
  async healthAreas(
    @graphql.Args() args: HealthAreaFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HealthArea[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "HealthArea",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => HealthArea, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "HealthArea",
    action: "read",
    possession: "own",
  })
  async healthArea(
    @graphql.Args() args: HealthAreaFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HealthArea | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "HealthArea",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => HealthArea)
  @nestAccessControl.UseRoles({
    resource: "HealthArea",
    action: "create",
    possession: "any",
  })
  async createHealthArea(
    @graphql.Args() args: CreateHealthAreaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HealthArea> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "HealthArea",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"HealthArea"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => HealthArea)
  @nestAccessControl.UseRoles({
    resource: "HealthArea",
    action: "update",
    possession: "any",
  })
  async updateHealthArea(
    @graphql.Args() args: UpdateHealthAreaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<HealthArea | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "HealthArea",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"HealthArea"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => HealthArea)
  @nestAccessControl.UseRoles({
    resource: "HealthArea",
    action: "delete",
    possession: "any",
  })
  async deleteHealthArea(
    @graphql.Args() args: DeleteHealthAreaArgs
  ): Promise<HealthArea | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Contributor])
  @nestAccessControl.UseRoles({
    resource: "HealthArea",
    action: "read",
    possession: "any",
  })
  async contributors(
    @graphql.Parent() parent: HealthArea,
    @graphql.Args() args: ContributorFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Contributor[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Contributor",
    });
    const results = await this.service.findContributors(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
